adoptium/TKG

- makefile
- change it back to TKG once test build file has been updated
> Temporarily change lib folder to TestConfig

- scripts/build_test.xml
- TestConfig needs to be copied to jvmtest folder for any BUILD_LIST
> Always call TestCongfig/build.xml

- scripts/moveDmp.pl
- scripts/resultsSum.pl
- Added moveTDUMP to move core dump to
TESTOUTPUT/<testname>
Signed-off-by: Jenny Chen <Jenny.Chen@ibm.com>
> Capture core dump for zos in post test step

- scripts/resultsSum.pl
- settings.mk
- cd into TKG/scripts and invoke resultsSum.pl
> Fix resultsSum perl INC issue on windows

- openj9Settings.mk
> Prepend test jvm lib dir to the LIBPATH

- scripts/resultsSum.pl
Update JenkinsFile to PLATFORM to match AdoptOpenJDK values
> Update JenkinsFile to PLATFORM

- scripts/moveDmp.pl
> Quiet dump move message on non zos platform

- scripts/getDependencies.pl
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>
> Correct dependency curl processing on zOS

- scripts/getDependencies.pl
ASM 7.3 includes support for JEP 359 Records (https://github.com/eclipse/openj9/issues/7945)
merge should coordinate with: https://github.com/eclipse/openj9/pull/8200
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>
> Upgrade asm-7.2 to asm-7.3

- .gitignore
- clean.mk
- compile.mk
- makeGen.mk
- makefile
- runtest.mk
- settings.mk
- src/org/testKitGen/MkGen.java
- src/org/testKitGen/Options.java
- src/org/testKitGen/TestInfo.java
- modify testKitGen to generate makefiles when executing target
- add .gitignore file
- issue: https://github.com/AdoptOpenJDK/TKG/issues/25
> Generate makefiles on the fly

- scripts/resultsSum.pl
> Add disabled in tap output

- makefile
- settings.mk
- move JAVA_HOME export to makefile
> Using TEST_JDK_HOME/java to launch ant for TKG compilation

- src/org/testKitGen/MkGen.java
- src/org/testKitGen/Options.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestTarget.java
- utilize TestTarget class to manage different types of target
> Add TestTarget class

- src/org/openj9/envInfo/JavaInfo.java
Signed-off-by: William Parker william.parker1@ibm.com
> Add support for RISC-V

- makeGen.mk
- makefile
- src/org/testKitGen/MainRunner.java
- src/org/testKitGen/MkGen.java
- src/org/testKitGen/Options.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestTarget.java
- support make _testList TESTLIST=<comma separated test names>
> Add ability to run a list of tests

- scripts/resultsSum.pl
> Utilize HUDSON_URL in rebuild link

- scripts/moveDmp.pl
- loop through regex matches if multiple dumps found
Fixes #48
> Fix the issue that only one dump archived on zos

- scripts/moveDmp.pl
> Remove confusing log msg in moveDmp.pl

- openj9Settings.mk
Issue: https://github.com/eclipse/openj9/issues/9231
> Remove default -Xcompressedrefs and -Xnocompressedrefs

- featureSettings.mk
- add ifndef before setting TEST_ITERATIONS
fixes #59
> Fix the issue with TEST_ITERATIONS

- makeGen.mk
- makefile
> Change option NUM_MACHINE to NUM_MACHINES

- src/org/testKitGen/TestDivider.java
- print out invalid test duration and use default value for such case
> Verify test duration queried from TRSS

- src/org/testKitGen/Options.java
- src/org/testKitGen/TestDivider.java
- add logic to divide tests based on testTime specified
> Adding testTime option for parallel linked with TRSS

- src/org/testKitGen/TestDivider.java
fixes: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/243
together with this PR https://github.com/AdoptOpenJDK/openjdk-test-tools/pull/244
[ci skip]
> Update TRSS api

- src/org/testKitGen/TestInfo.java
- disabled test was executed when included in the testList
- change the behavior that the disabled test will not be executed
> Update the testList behavior with disabled test

- scripts/getDependencies.pl
-removes platform specific code
-no longer use wget, only curl
resolves: #68
signed-off-by: nikolamilijevic 1 <nmilijev@uwaterloo.ca>
> Remove platform specific code in getDependencies script

- src/org/testKitGen/DirectoryWalker.java
> Fix the no test issue when currentdir is empty

- scripts/resultsSum.pl
- settings.mk
- replace hardcoded map with the properties file
> Utilizing buildPlatformMap.properties in resultsSum.pl

- moveDmp.mk
- scripts/moveDmp.pl
- Added archive core files for all non-zos platforms
Issue: AdoptOpenJDK/openjdk-tests/issues/1564
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>
> Added archive core files for all platforms except zos

- src/org/testKitGen/Constants.java
- src/org/testKitGen/TestDivider.java
- when TRSS is not accessible, fall back to use cached data
- when TRSS data is not complete, use cached data as complement
- code refactor for TestDivider class
> Parallel backup approach: cached duration data

- src/org/testKitGen/Arguments.java
- src/org/testKitGen/DirectoryVisitor.java
- src/org/testKitGen/DirectoryWalker.java
- src/org/testKitGen/MainRunner.java
- src/org/testKitGen/MkGen.java
- src/org/testKitGen/ModesDictionary.java
- src/org/testKitGen/ParallelGenVisitor.java
- src/org/testKitGen/PlaylistInfo.java
- src/org/testKitGen/TestDivider.java
- src/org/testKitGen/TestGenVisitor.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/UtilsGen.java
- src/org/testKitGen/Variation.java
- move count logic into TestInfo class
- add interface DirectoryVisitor to decouple the traversal and generate logic
- rename Options to Arguments
- rename Utils to UtilsGen
> Refactor TKG

- scripts/getDependencies.pl
Merge needs to be coordinated with: https://github.com/eclipse/openj9/pull/10057
- this includes support for Java 15 preview features
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>
> Upgrade ASM version to 8.0.1

- .gitignore
- src/org/testKitGen/Constants.java
- src/org/testKitGen/TestDivider.java
> Add additional folder for cached TRSS data

- src/org/openj9/envInfo/JavaInfo.java
Fixes #18 
Signed-off-by: Shelley Lambert <slambert@gmail.com>
> Add case for os.arch equals 'arm'

- scripts/getDependencies.pl
Upgrade ASM for JEP 360 sealed classes tests (again). Latest version contains recent spec changes.
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>
> Upgrade to ASM 9

- makeGen.mk
- makefile
- src/org/testKitGen/Arguments.java
- src/org/testKitGen/CleanVisitor.java
- src/org/testKitGen/MainRunner.java
- src/org/testKitGen/TestDivider.java
- src/org/testKitGen/UtilsGen.java
- clean mode removes all the generated files
> Add a clean mode in TKG

- src/org/testKitGen/MkGen.java
- src/org/testKitGen/TestDivider.java
- src/org/testKitGen/TestTarget.java
- use diabled.testname to run disabled test
> Simplify disabled single test behavior

- src/org/testKitGen/Arguments.java
> Remove trailing slash from TRSS_URL

- src/org/openj9/envInfo/MachineInfo.java
- Added checks to make sure all openj9 prerequisites are met on the machine
Signed-off-by: Nikola Milijevic <nmilijev@uwaterloo.ca>
> Check that all openj9 prerequisites are up-to date on machine

- src/org/testKitGen/TestDivider.java
- merge local and TRSS solution
> Simplify parallel list generation

- src/org/openj9/envInfo/MachineInfo.java
> Fix ant problem on windows

- scripts/testBot/autoModifier.py
- scripts/testBot/disable.py
- add the scripts that can automatically insert disable line
> Add test bot tool

- testEnv.mk
Also set silent JIT ENV such that no message will be printed out
Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>
> Enable DF flag diagnostic check

- scripts/resultsSum.pl
Signed-off-by: OscarQQ <Yixin.Qian@ibm.com>
> provide one link to run all failed tests

- src/org/testKitGen/MkGen.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestInfoParser.java
- src/org/testKitGen/TestTarget.java
- src/org/testKitGen/Variation.java
- allow user to disable a variation
> Add more granularity for disabled feature

- .gitignore
- scripts/testBot/disable.py
- scripts/testBot/playlistModifier.py
- use an xml parser to replace the regex match
- add variation disable
- add a format function
> Update testBot disable function

- makefile
- scripts/build_test.xml
- scripts/build_tools.xml
- scripts/getDependencies.pl
- scripts/getDependencies.xml
related: https://github.com/AdoptOpenJDK/TKG/issues/63
Signed-off-by: OscarQQ <Yixin.Qian@ibm.com>
> Move functional tests related 3rd party libs into functional level

- scripts/getDependencies.xml
related: https://github.com/AdoptOpenJDK/TKG/issues/63
Signed-off-by: OscarQQ <Yixin.Qian@ibm.com>
> add absolute path to getDependcies.pl

- src/org/testKitGen/PlaylistInfoParser.java
- src/org/testKitGen/TestInfoParser.java
- add impl and version elements
- user can write a combination of impl, version and variation in disable block
- error msg on specifying one element more than once in one disable block
> Support disabling impl and java version

- resources/ottawa.csv
Resolves: https://github.com/eclipse/openj9/issues/11291
> Add Mode145 in Ottawa.csv

- resources/modes.xml
- resources/ottawa.csv
Add Mode645 -Xcompressedrefs -Xgcpolicy:gencon -Xshareclasses -Xjit
Related: https://github.com/eclipse/openj9/issues/11105
> Add Mode645 in TKG

- src/org/openj9/envInfo/CmdExecutor.java
- src/org/openj9/envInfo/EnvDetector.java
- src/org/openj9/envInfo/JavaInfo.java
- src/org/openj9/envInfo/MachineInfo.java
> Detect mixed reference in envDetector

- scripts/testBot/disable.py
- scripts/testBot/playlistModifier.py
- update testbot code to support impl and ver disable
> Support auto disable impl and version

- scripts/testBot/playlistModifier.py
> Fix boundary case for auto disable tool

- scripts/build_test.xml
closed: https://github.com/AdoptOpenJDK/TKG/issues/63
Signed-off-by: OscarQQ <Yixin.Qian@ibm.com>
> remove get all dependency at the beginning

- src/org/testKitGen/Arguments.java
- src/org/testKitGen/TestDivider.java
- src/org/testKitGen/TestInfoParser.java
> Support disable specific platform

- scripts/testBot/playlistModifier.py
> Add platform auto exclusion feature

- resources/modes.xml
- resources/ottawa.csv
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2137#issuecomment-758007659
> Add Mode1000 (NoOptions on 32bit platforms)

- scripts/resultsSum.pl
- settings.mk
> Revert "Generate TAP file if there are no tests for the given target"

- src/org/openj9/envInfo/Info.java
- src/org/openj9/envInfo/MachineInfo.java
> Shorten test_output folder name to output

- scripts/build_test.xml
Conditionally set properties based on whether or not another property is
set to a non-empty value.
> Add a macro to conditionally set properties.

- src/org/openj9/envInfo/Info.java
- src/org/openj9/envInfo/MachineInfo.java
- encapsulate detected info into Class
- add assertion for some of the prerequisites
Signed-off-by: renfeiw renfeiw@ca.ibm.com
> Update machineInfo detection

- scripts/testBot/disable.py
- scripts/testBot/playlistModifier.py
- src/org/testKitGen/TestInfoParser.java
> Add feature to disable vendor

- src/org/testKitGen/TestInfoParser.java
- add an assert to make sure comment is provided
> Remove support for old style of disable

- scripts/testBot/disable.py
- use shlex to split in case the argument contains quoted string
> Cover the corner case in auto disable tool

- README.md
- playlist.xsd
- scripts/testBot/playlistModifier.py
- src/org/testKitGen/TestInfoParser.java
> Convert subset to version

- src/org/openj9/envInfo/MachineInfo.java
> Use mac specific cpu command in MachineInfo

- scripts/testBot/disable.py
- scripts/testBot/playlistModifier.py
> Auto update copyright for auto exclusion

- scripts/getDependencies.pl
> Update asmtools location

- scripts/getDependencies.pl
related: https://github.com/eclipse/openj9/issues/12284
> add third party jython lib

- src/org/testKitGen/TestInfoParser.java
- completely switch to version
> Remove temp support for subset

- resources/modes.xml
- resources/ottawa.csv
> add mode 616

- scripts/liveMonitor_countTests/count-java-tests.py
- scripts/liveMonitor_countTests/jtreg-monitor.py
#176 
I added the report and scripts under a folder named liveMonitor_countTests in scripts folder.
Signed-off-by: Mehmet Geylani <barankara5@gmail.com>
Co-authored-by: Mat Carter @macarte
> Fixed version of scripts added

- scripts/testBot/playlistModifier.py
- src/org/testKitGen/TestInfoParser.java
> Change plat to platform for disable feature

- .github/workflows/runAqa.yml
> Set up jdksource correctly if sdk_resource='build-jdk'

- src/org/testKitGen/PlaylistInfoParser.java
> turn on playlist validation

- resources/playlist.xsd
> Add platform in playlist.xsd

- settings.mk
issue: https://github.com/eclipse-openj9/openj9/issues/12878
Signed-off-by: Hang Shao <hangshao@ca.ibm.com>
> Add exclude file for value type standard build

- scripts/getDependencies.pl
Fixes: https://github.com/adoptium/TKG/issues/203
> Update tohandler_simple url in getDependencies

- src/org/openj9/envInfo/JavaInfo.java
This PR fixes #208 
Signed-off-by: Pasam Soujanya psoujany@in.ibm.com
> Detecting zLinux31 architecture

- src/org/openj9/envInfo/MachineInfo.java
Fixes the currently broken CPU detection for Solaris
> Add CPU detection for Solaris

- scripts/testBot/runAqaArgParse.py
Fixes: https://github.com/adoptium/TKG/issues/212
> Update repo URL in runAqaArgParse

- scripts/getDependencies.pl
> Update jtreg jar

- .github/workflows/runAqa.yml
- .github/workflows/runAqaConfig.json
- scripts/testBot/runAqaArgParse.py
> Add option to parse customized openj9 repo and branch in runAqa

- .github/workflows/runAqa.yml
> Pass openj9_repo into runAqa action

- scripts/testBot/playlistModifier.py
> Update auto disable to use new format

- src/org/openj9/envInfo/JavaInfo.java
> Fix issue with compressed detection

- src/org/openj9/envInfo/JavaInfo.java
> Support updated ibm vendor

- src/org/testKitGen/TestInfoParser.java
> Remove temporary support for plat

- src/org/testKitGen/TestInfoParser.java
- use common function getImmediateChildContent
- reorganize aot parser logic
> Add function getImmediateChildContent in TKG for better parsing

- settings.mk
related: https://github.com/adoptium/temurin-build/pull/2675#pullrequestreview-732986327
> Define JRE_IMAGE

- resources/playlist.xsd
> Update playlist.xsd for stricter validation

- resources/playlist.xsd
Reverts adoptium/TKG#229 until the release branch has passed the test.
> Revert "Update playlist.xsd for stricter validation"

- makefile
> Clean build files before compilation

- scripts/getDependencies.pl
> Add jtreg-6.1+1.tar.gz for jdk18

- scripts/getDependencies.pl
> Update jtreg6.1.1 name

- scripts/moveDmp.pl
> Move all diagnostic files in moveDmp.pl

- .github/workflows/runAqaConfig.json
- scripts/testBot/runAqaArgParse.py
- when sdk_resource is nightly
> Add default customized_sdk_url for openj9 workflow

- src/org/testKitGen/MkGen.java
> Add target level TEST_ITERATIONS for AOT test

- resources/playlist.xsd
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestInfoParser.java
- supports turn on/off test based on feature
- combine existing <aot> tag with feature tag
Fixes #268 
> Add feature into TKG

- src/org/openj9/envInfo/EnvDetector.java
- src/org/openj9/envInfo/JavaInfo.java
Add 'java -version' to the metadata file.
Fixes: adoptium/TKG#260
Signed-off-by: Jerome Ju jeromeqju@gmail.com
> Add java -version output

- src/org/openj9/envInfo/JavaInfo.java
Fixes the -version arg in execution.
Fixes: https://github.com/adoptium/TKG/issues/277
Signed-off-by: Jerome Ju [jeromeqju@gmail.com](mailto:jeromeqju@gmail.com)
> Fix -version args in Javainfo

- envSettings.mk
- settings.mk
- src/org/openj9/envInfo/EnvDetector.java
- src/org/openj9/envInfo/JavaInfo.java
- auto detect criu
- add CRIU into TEST_FLAG
- generate detected TEST_FLAG
> Auto detect TEST_FLAG

- src/org/testKitGen/MkGen.java
> Auto include testVar.mk in playlist

- scripts/resultsSum.pl
> Add timestamp in tap file

- src/org/openj9/envInfo/EnvDetector.java
- src/org/openj9/envInfo/JavaInfo.java
Add release info for AQA-Cert
Fixes: https://github.com/adoptium/TKG/issues/260
Signed-off-by: Jerome Ju [jeromeqju@gmail.com](mailto:jeromeqju@gmail.com)
> Add release info to the metadatafile for AQA-Cert

- scripts/testBot/runAqaArgParse.py
Added condition checks for runAqa Json file. Skip if there's no such file.
Fixes: #219 
Signed-off-by: Jerome Ju [jeromeqju@gmail.com](mailto:jeromeqju@gmail.com)
> Add condition for runAqa config Json file

- openj9Settings.mk
Remove TR_Options setting for zNext.
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>
> Remove environment setting for zNext.

- scripts/liveMonitor_countTests/README.md
Add basic documentations and usage regarding user stories for the liveMonitor scripts
Fixes: https://github.com/adoptium/TKG/issues/280
Signed-off-by: Jerome Ju [jeromeqju@gmail.com](mailto:jeromeqju@gmail.com)
> Add Readme.md for the liveMonitor scripts

- scripts/resultsSum.pl
Close: #289 
Sign off: Yee Lin
> Display rebuild link in local case only

- scripts/testBot/disable.py
- scripts/testBot/playlistModifier.py
> Support auto disable multiple tests in one comment

- src/org/testKitGen/TestCategory.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestList.java
- src/org/testKitGen/Variation.java
- generate parallel list with disabled tests inside
> Support parallel on disabled targets

- src/org/testKitGen/PlaylistInfoParser.java
- avoid compiling skipped or disabled test
> Refine dynamic compilation

- envSettings.mk
- src/org/openj9/envInfo/JavaInfo.java
> Avoid duplicating testflag in auto detection

- src/org/openj9/envInfo/JavaInfo.java
> Fix issue with test flag detection

- src/org/openj9/envInfo/JavaInfo.java
> Add autodetection for VTStandard

- scripts/build_test.xml
- scripts/getFileWithRetry.sh
> Add functions to get file with retry

- src/org/openj9/envInfo/JavaInfo.java
Related https://github.com/adoptium/aqa-tests/issues/3683
> Support Red Hat jdk_vendor

- scripts/build_test.xml
- added quotes
- added attribute dest
> Update getFileWithRetry macrodef

- src/org/testKitGen/MainRunner.java
> Fail when test cannot be found in testList

- resources/ottawa.csv
- revert entry that was accidently changed
> Fix ottawa.csv

- examples/base/playlist.xml
- examples/hierarchy/a1/b1/playlist.xml
- examples/hierarchy/a2/b2/c2/playlist.xml
- examples/hierarchy/a2/b2/playlist.xml
- examples/hierarchy/a2/d2/playlist.xml
- examples/hierarchy/a2/playlist.xml
- examples/hierarchy/a3/b3/playlist.xml
- examples/hierarchy/a3/c3/d3/playlist.xml
- examples/hierarchy/a3/f3/playlist.xml
- examples/sliceAndDice/level/playlist.xml
- scripts/testTKG/testRunner.py
- test framework
- test base, hierarchy and sliceAndDice
> Initial test for TKG

- src/org/testKitGen/Arguments.java
- print useful message to replace null point exception
> Add error handling when spec not found

- envSettings.mk
- makeGen.mk
- src/org/openj9/envInfo/EnvDetector.java
- src/org/openj9/envInfo/MachineInfo.java
- src/org/testKitGen/Arguments.java
- src/org/testKitGen/TestInfoParser.java
- update EnvDetector and MachineInfo to support microArch
- add detection for skylake
- add parsing logic in TKG to check microArch
- update corresponding make files
related: #336
> Support microArch

- examples/platformRequirements/playlist.xml
- resources/playlist.xsd
- scripts/testTKG/testRunner.py
- src/org/testKitGen/Arguments.java
- src/org/testKitGen/MkGen.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestInfoParser.java
Closes #350 
- create parsing logic
- add new test
> Support OR logic for platformRequirements

- src/org/openj9/envInfo/MachineInfo.java
> Adding docker info into env detection

- scripts/resultsSum.pl
resolves: #348
signed-off-by: Moman Malik <momanmalik@ibm.com>
> Add customTarget to TAP file

- scripts/resultsSum.pl
fixes: [#3792](https://github.com/adoptium/aqa-tests/issues/3792)
> Update resultSum parsing logic

- scripts/getDependencies.pl
Related https://github.com/adoptium/aqa-tests/issues/3965
> Add dependency jtreg7

- scripts/resultsSum.pl
> Show success rate in result summary

- settings.mk
- exit when success is detected
> Add exit condition for repeat feature

- scripts/resultsSum.pl
Fixes https://github.com/adoptium/TKG/issues/301
- exit 2 when test failed
- exit 3 when there's no test
> Exit non zero code when there is test failure

- scripts/resultsSum.pl
- remove success rate from rerun links
- add success rate as a tap comment
> Fix test name in rerun link

- scripts/resultsSum.pl
Relates https://github.com/adoptium/aqa-tests/issues/4146#issuecomment-1317735832
> Add failures summary information

- src/org/openj9/envInfo/JavaInfo.java
Related with https://github.com/adoptium/aqa-tests/issues/4155 
https://github.com/adoptium/aqa-tests/pull/4159
> Support Microsoft as JDK_Vendor

- settings.mk
- src/org/testKitGen/Arguments.java
- src/org/testKitGen/MkGen.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestInfoParser.java
- handle TKG_ITERATIONS and AOT_ITERATIONS in the nested loops
- add set up/tear down inbetween TKG_ITERATIONS
- no set up/tear down inbetween AOT_ITERATIONS
- AOT_ITERATIONS will not continue after failure
> Update iteration feature

- settings.mk
> Revert "Create/clean tmp dir for test"

- scripts/getDependencies.pl
https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline/638/
> Fix jtreg 7.1.1+1 url

- scripts/getDependencies.pl
> Update asmtools link

- scripts/remove_duplicate_tests.py
Resolves #392 
Signed-off-by: ArkaprabhaChakraborty <chakrabortyarkaprabha998@gmail.com>
> Add python script to remove duplicate tests

- scripts/getDependencies.pl
- scripts/resultsSum.pl
Linked to https://github.com/adoptium/infrastructure/issues/2932
> Change references of ci.adoptopenjdk.net to ci.adoptium.net

- .github/workflows/testTKG.yml
- run tkg test with comment "run tkg-test [TEST_OPTIONS]" in PR
> Add github action to run TKG test

- scripts/resultsSum.pl
Update to work with format *.java#.* 
For example java/nio/channels/vthread/BlockingChannelOps.java#direct-register
> Update testcase naming matching regex

- .github/workflows/testTKG.yml
- envSettings.mk
- examples/platformRequirements/playlist.xml
- makeGen.mk
- scripts/testTKG/testRunner.py
- settings.mk
- src/org/openj9/envInfo/EnvDetector.java
- src/org/openj9/envInfo/MachineInfo.java
- src/org/testKitGen/Arguments.java
- src/org/testKitGen/TestInfoParser.java
- supported os: rhel, ubuntu, sles
- add logic in machine detection code
- add logic in TKG makeGen to support user specified os
- add tkg tests
fixes #417
> Support user specified OS name and version

- scripts/resultsSum.pl
Description
This adds the machine name to TAP file
This PR fixes https://github.com/adoptium/TKG/issues/404
Signed-off-by: Shriti Chandra [shchandr@redhat.com](mailto:shchandr@redhat.com)
> Add machine name to TAP file

- src/org/openj9/envInfo/MachineInfo.java
- supports cent os
- fix supported os logic
Fixes #436
> Update osLabel detection

- scripts/getDependencies.pl
Relate https://github.com/adoptium/aqa-tests/issues/4548
> Add jtreg7.2

- scripts/testTKG/testRunner.py
- scripts/testTKG/test_base.py
- scripts/testTKG/test_hierarchy.py
- scripts/testTKG/test_jdkVersion.py
- scripts/testTKG/test_level.py
- scripts/testTKG/test_platformRequirements.py
- scripts/testTKG/utils.py
> Modularizing TKG test

- .gitignore
- examples/rerun/playlist.xml
- examples/rerun/rerunSub/playlist.xml
- resources/playlist.xsd
- scripts/testTKG/test_rerun.py
- src/org/testKitGen/BuildListGenVisitor.java
- src/org/testKitGen/CleanVisitor.java
- src/org/testKitGen/Constants.java
- src/org/testKitGen/DirectoryVisitor.java
- src/org/testKitGen/DirectoryWalker.java
- src/org/testKitGen/MainRunner.java
- src/org/testKitGen/ParallelGenVisitor.java
- src/org/testKitGen/PlaylistInfo.java
- src/org/testKitGen/PlaylistInfoParser.java
- src/org/testKitGen/TestGenVisitor.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestInfoParser.java
- src/org/testKitGen/UtilsGen.java
- update the parsing logic
- update the util gen logic to generate IGNORE_ON_RERUN
- add corresponding test case
> Add support for rerun tag in TKG

- src/org/openj9/envInfo/CmdExecutor.java
- src/org/openj9/envInfo/MachineInfo.java
> Revert "Fix machineInfo curl validation"

- scripts/getDependencies.pl
See also https://github.com/adoptium/ci-jenkins-pipelines/pull/792, on which this depends.
> Also download jtreg-7.3.1+1

- scripts/getDependencies.pl
- Remove unsued 3rd party jars in TKG
- Related Issue: https://github.com/adoptium/TKG/issues/468
> Remove unsued 3rd party jars in TKG

- makeGen.mk
- makefile
This PR needs to be merged with https://github.com/adoptium/aqa-tests/pull/4908
related: https://github.com/adoptium/aqa-tests/issues/4500
resolves: https://github.com/adoptium/TKG/issues/478
> Pass LIB_DIR in genParallelList

- makefile
- settings.mk
Fix https://github.com/adoptium/aqa-tests/issues/4914
> Moving LIB_DIR visible for all make process

- src/org/openj9/envInfo/JavaInfo.java
Related https://github.com/adoptium/TKG/issues/502
Update getJDKVendor()
> Add Fujitsu

- scripts/getDependencies.pl
- As required from issue 5073: https://github.com/adoptium/aqa-tests/issues/5073 for adding new Mockito test case
- Add 3 more dependencies accordingly.
> Add build dependencies for Mockito testcase

- scripts/getDependencies.pl
Remove maven_jar_plugin dependence as of last PR: https://github.com/adoptium/TKG/pull/505
> Remove maven_jar_plugin dependence

- scripts/getDependencies.pl
shasum 200da75e67689e8a604ec6fe9a6f55b2c000b6ce
Fixes #514
> Update to latest version of jcstress.jar

- scripts/getDependencies.pl
to unblock issue 19122
Fix: https://github.com/eclipse-openj9/openj9/issues/19122#issuecomment-1995914316
> Remove mockito-core and byte_buddy 

- .github/workflows/testTKG.yml
Add GH permissions
- Add GH action permissions for testTKG job
> Update GH permissions

- .github/workflows/testTKG.yml
- Update the content permission to `write` for testTKG job
> Update the Github Actions permission

- scripts/resultsSum.pl
> Parse numbers with comma and remove extra new lines

- resources/ottawa.csv
This commit disables Modes 155, 159, 198, and 199 on AArch64 Linux.
Fixes: #529
> Disable Modes 155, 159, 198, and 199 on AArch64 Linux

- scripts/getDependencies.pl
- Added dependencies for MockitoTest case
- Issue to: https://github.com/adoptium/aqa-tests/issues/5073
> Added dependencies for MockitoTest case

- examples/platformRequirements/playlist.xml
related: https://github.com/adoptium/TKG/issues/471
> Added example test case for ^arch_390_z15+

- src/org/testKitGen/TestDivider.java
- Added `-L` to support http TRSS URL.
resolves: https://github.com/adoptium/TKG/issues/555
> Add follow redirect in querying

- src/org/openj9/envInfo/MachineInfo.java
Issue related to: https://github.com/adoptium/TKG/issues/567
> Added mvn check

- scripts/getDependencies.pl
- scripts/getDependencies.xml
Depends on https://github.com/adoptium/ci-jenkins-pipelines/pull/1051.
> Also download jtreg-7.4+1

- src/org/openj9/envInfo/MachineInfo.java
Issue related to: https://github.com/adoptium/TKG/issues/547
Signed-off-by: sophiaxu0424 [xuminghong0424@gmail.com](mailto:xuminghong0424@gmail.com)
> Added bash version check

- src/org/openj9/envInfo/JavaInfo.java
This will help JFR related tests in the future.
Related: https://github.com/eclipse-openj9/openj9/pull/19917
> Add JFR check to test flags

- src/org/testKitGen/MkGen.java
related: backlog/issues/1529 and https://github.com/adoptium/aqa-tests/pull/5662
> Add FIPS_VARIATION_PROBLEM_LIST_FILE support

- scripts/getDependencies.pl
Fixes #546 
cc
@llxia 
@smlambert
> Removed view/Dependencies from asmtools URL

- scripts/resultsSum.pl
> Replace Win delimiters

- resources/ottawa.csv
- Update ottawa csv file for Mode150-CS & Mode110-CS to run CS on all platforms.
related:https://github.ibm.com/runtimes/backlog/issues/597
> Update ottawa csv file for Mode150-CS & Mode110-CS
