adoptium/TKG

- settings.mk
- use TestConfig as it contains testng log property file
> Change RESOURCES_DIR path

- makefile
- scripts/moveDmp.pl
- Added moveTDUMP to move core dump to
REPORTDIR/compile
Signed-off-by: Jenny Chen <Jenny.Chen@ibm.com>
> Capture core dump for z/os in test compilation

- settings.mk
Update ARCH and BITS parser to work with SPEC linux_aarch64. So
JVM_OPTION could be set properly. 
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>
> Update ARCH and BITS parser

- scripts/build_test.xml
- scripts/getSHA.sh
There are cases that expected repo_dir doesn't exist. Add the check to ensure SHA information is correct.
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>
> Add check if repo directory exists

- makefile
- settings.mk
- use TKG folder to store lib files
> Update lib dir location

- testEnv.mk
-XX:StartAsJITServer option has been removed. It has been replaced
by jitserver launcher.
Signed-off-by: Ashutosh Mehra <mehra.ashutosh@ibm.com>
> Use jitserver launcher to start JVM in server mode

- makefile
- runtest.mk
- scripts/resultsSum.pl
- move failed and test target
- remove runtest target
- include settings.mk in failedtargets.mk
> Fix failed and test target

- settings.mk
- using slash in autoGen.mk path
- add quotation around autoGen.mk
> Fix path issue for certain windows machines

- openj9Settings.mk
In order to find libwrappers.so
Closes #51
Testing
- shrtest job/Grinder_zos/9 - passed
- sanity.functional job/Grinder_zos/10 - no test summary was created
> z/OS needs jdk/lib in ADD_JVM_LIB_DIR_TO_LIBPATH

- .gitignore
- makeGen.mk
- makefile
- scripts/build_tools.xml
- scripts/resultsSum.pl
- src/org/testKitGen/Constants.java
- src/org/testKitGen/DirectoryWalker.java
- src/org/testKitGen/MainRunner.java
- src/org/testKitGen/MkGen.java
- src/org/testKitGen/Options.java
- src/org/testKitGen/PlaylistInfo.java
- src/org/testKitGen/TestDivider.java
- running mode parallelList, it will split tests and generate parallelList.mk
- we can run testList_<index> target in parallelList.mk to invoke splitted list
- add new mode: parallelList and additional options
- rename MkTreeGen to DirectoryWalker and modify it to support both modes
- restructure MkGen and separate PlaylistInfo from it
- add TestDivider to handle parallelList generation
- modify makefiles and build files
> Generate parallel list locally

- scripts/build_tools.xml
- since child build might do make clean before executing tests
- rely on FileWrite() to overwrite parallel.mk when genParallel
> Remove parallel.mk from clean step

- makefile
For parallel runs, genParallelList only needs to call compileTools
Issue: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1563
> make compileTools a separate target

- compile.mk
- makeGen.mk
- makefile
- resources/buildPlatformMap.properties
- scripts/build_tools.xml
- scripts/getDependencies.pl
- scripts/resultsSum.pl
- src/org/testKitGen/Constants.java
- src/org/testKitGen/MainRunner.java
- src/org/testKitGen/ModesDictionary.java
- src/org/testKitGen/Options.java
- src/org/testKitGen/TestDivider.java
- add option TRSS_URL
- update numOfMachine to numOfMachines
- use buildPlatformMap.properties to map SPEC to build platform
- use curl command to get test duration from TRSS
- handle different failure cases when retrieving duration data
- print test duration status
- update default test duration
- use two priority queues to split the tests based on duration
- remove dependencies of EnvDectector for getDependencies
- use json-simple for parsing json result and add it in getDependencies
- update getDependencies to have more precise error info
- fix minor issue with resultsSum
> Link TRSS for dynamic paralellization

- resources/ottawa.csv
Update Mode107-OSRG to match Mode107 value on linux_ppc-64_cmprssptrs_le
and linux_ppc-64_le
Fixes: https://github.com/eclipse/openj9/issues/9579
> Update Mode107-OSRG to match Mode107 value

- makefile
- moveDmp.mk
- scripts/moveDmp.pl
- remove SPEC dependency from moveDmp.pl
- separate envDectect from compileTools target
- move moveDmp commands into moveDmp.mk
- add moveDmp command in compileTools target
Fixes #66
> Parse core from TKG and envDetector compilation

- src/org/testKitGen/DirectoryWalker.java
- current logic fails when multiple folders start with same string
Fixes #77
> Fix the buildList checking logic

- scripts/getDependencies.pl
The openj9jtregtimeouthandler.jar is used to replace the default timeout
handler, when running OpenJDK tests on OpenJ9. It uses an OpenJ9 command
to create a core file in addition to running jstack.
Issue https://github.com/eclipse/openj9/issues/9651
Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>
> Include openj9jtregtimeouthandler.jar in dependencies

- scripts/getDependencies.pl
- use a generic name, so we do not need to update all references when we
update this jar
Related: https://github.com/AdoptOpenJDK/TKG/issues/90
> Rename asm-8.0.1.jar to asm.jar

- openj9Settings.mk
Related: https://github.com/eclipse/openj9/pull/10291
> Set ARCH_DIR for aarch64

- src/org/openj9/envInfo/MachineInfo.java
- added code to ouptut the version of openj9 prerequisites ant, make, curl and perl in MachineInfo
Signed-off-by: Nikola Milijevic <nmilijev@uwaterloo.ca>
> Add checks for openj9 test prerequsites

- moveDmp.mk
I don't believe any platforms require the `-n` to be specified on `tail` so this shouldn't impact anything else. I need this change in before I can let https://github.com/AdoptOpenJDK/openjdk-tests/pull/2039 go in (that PR currently hard codes the TKG repo to this branch, so once this PR is merged I can remove that from the other one)
Signed-off-by: Stewart X Addison <sxa@redhat.com>
> moveDmp: stop using -n on tail as it is not required and breaks on Solaris

- scripts/getDependencies.pl
- osgi jar file is used by CDSAdaptorTest
- Related to Runtimes/Backlog 394
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>
> added downloading osgi jar file

- scripts/getDependencies.pl
- Update osgi jar link
- Depends: https://github.com/eclipse/openj9/pull/11520
- Related: https://github.com/AdoptOpenJDK/run-aqa/issues/62
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>
> Update osgi jar link

- resources/ottawa.csv
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2137
> Disable Mode650 on 32-bit platforms

- scripts/resultsSum.pl
- settings.mk
Fixes https://github.com/AdoptOpenJDK/TKG/issues/138
If no test targets match the given target, then a TAP file is still produced.
Signed-off-by: Andrew Leonard <anleonar@redhat.com>
> Generate TAP file if there are no tests for the given target

- envSettings.mk
- makeGen.mk
- scripts/resultsSum.pl
- settings.mk
- src/org/openj9/envInfo/EnvDetector.java
- src/org/openj9/envInfo/JavaInfo.java
- src/org/testKitGen/Arguments.java
- src/org/testKitGen/TestInfoParser.java
- TKG will check if JDK_VENDOR matches vendor defined in playlist
> Add jdk vendor in TKG

- src/org/testKitGen/TestInfoParser.java
- use getElements instead of getElementsByTagName
- getElementsByTagName can accidentally grab elements from `<disabled>` tag
> Fix issues regarding impl and subset filter

- envSettings.mk
- makefile
- If AUTO_DETECT is set to false, still run auto detection
- Use auto detected value when the environment variable is not set
> Change default behavior of auto detection

- envSettings.mk
- when AUTO_DETECT is on, override SPEC without error check
> Update auto detect behavior

- scripts/getDependencies.pl
I don't expect the leading space in `url => ' https...'` was intentional (and I'm surprised it didn't fail).
Also remove trailing whitespace, repeated blank lines.
> Remove unwanted spaces in URLs

- .github/workflows/runAqa.yml
- .github/workflows/runAqaArgParse.py
As per AdoptOpenJDK/openjdk-tests#2399, adds the Run AQA (Comment-Triggered PR Builds) workflow to the TKG repo.
When ran on a PR in this (TKG) repo, the [AdoptOpenJDK/run-aqa@v1](https://github.com/AdoptOpenJDK/run-aqa) GitHub action is ran with the `tkg_Repo` argument set to the head of the PR.
> Add Run AQA (Comment-Triggered PR Builds) workflow

- .github/workflows/runAqa.yml
- .github/workflows/runAqaArgParse.py
- .github/workflows/runAqaConfig.json
- scripts/testBot/runAqaArgParse.py
Builds on top of PR #170 
Move the `runAqaArgParse.py` into `scripts/testBot` as a common place to not duplicate the code for multiple repos (as suggested by @renfeiw)
Add a configuration file `.github/workflows/runAqaConfig.json` for repository-specific defaults (as suggested by @smlambert). Currently only enables/disables arguments for custom TKG and openjdk-tests repos. Can be amended with more options later down the line as needed.
Change the AdoptOpenJDK/run-aqa@v1 action to [adoptium/run-aqa@v1](https://github.com/adoptium/run-aqa). Simply a renaming, no change in functionality.
Add the option to specify a custom openjdk-tests repo to pass to the [adoptium/run-aqa@v1](https://github.com/adoptium/run-aqa) action which is used to run AQA.
**Note for testing**: The `runAqaArgParse.py` …
> Add configuration file and custom openjdk-test repo option to Run AQA workflow

- scripts/testBot/runAqaArgParse.py
The previous default value for `--openjdk_testrepo` did not include a branch and therefore was invalid, which caused builds using the default openjdk_testrepo to fail.
**Note for testing**: This PR changes `runAqaArgParse.py` but the workflow will continue to use the unchanged `runAqaArgParse.py` from `adoptium:master`. Therefore, for testing, [line 29 of `runAqa.yml`](https://github.com/adoptium/TKG/blob/master/.github/workflows/runAqa.yml#L29) should be changed to match your/my personal repo which has the updated `runAqaArgParse.py`.
> Fix default value for openjdk_testrepo in Run AQA workflow script

- scripts/testBot/runAqaArgParse.py
Add a `--help` / `-h` argument to the Run AQA workflow (#170) which links to its documentation: 
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/RunAqa.md
This PR implements the same functionality of AdoptOpenJDK/openjdk-tests#2457
**Note for testing**: This PR changes `runAqaArgParse.py` but the workflow will continue to use the unchanged `runAqaArgParse.py` from `adoptium:master`. Therefore, for testing, [line 29 of `runAqa.yml`](https://github.com/adoptium/TKG/blob/master/.github/workflows/runAqa.yml#L29) should be changed to match your/my personal repo which has the updated `runAqaArgParse.py`.
> Add help command for a link to documentation in the Run AQA workflow

- resources/buildPlatformMap.properties
> Add arm64_mac in properties file

- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestInfoParser.java
- the new feature utilize regex to specify platform
fixes https://github.com/adoptium/TKG/issues/166
> Enhance platform requirements mechanism

- .github/workflows/runAqa.yml
- scripts/testBot/runAqaArgParse.py
This PR builds on top of #170: Run AQA (Comment-Triggered PR Build) workflow
- Change the `Echo parameters` step to simply echo the entire JSON of build parameters instead of each individual value in addition to it.
- Reduce redundant checkouts by using the fact that the current repo is the TKG repo. This also removes the need to modify the TKG checkout action to test changes to `runAqaArgParse.py`.
- Implement a new sdk_resource `build-jdk` which uses the [AdoptOpenJDK/build-jdk](https://github.com/AdoptOpenJDK/build-jdk/) action to build a JDK using a provided openjdk-build repo.
This functionality was requested in issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/2296 but was blocked due to issue https://github.com/AdoptOpenJDK/build-jdk/issues/24 which is still unresolved, …
> Run AQA Workflow: Implement build-jdk sdk_resource, Remove redundant checkouts

- scripts/getDependencies.pl
I have added the suggested section in the getDependencies.pl file and removed the download jtreg.jar logic from the build.xml file. Please review both the pull request made for [issue](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2484).
> Update getDependencies.pl to move download jtreg.jar logic in getDependencies

- settings.mk
Append `feature_ojdkmh_exclude.txt` to `EXCLUDE_FILE` if OJDK MHs are enabled.
TODO: eclipse-openj9/openj9#12811
Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>
> Append feature_ojdkmh_exclude.txt to EXCLUDE_FILE

- resources/playlist.xsd
- src/org/testKitGen/TestInfoParser.java
- use a element to encapsulate all disable items
- for more clarity
- to allow more stricter rule(maxOccurs) of xsd validation in future
> Update disable format

- resources/buildPlatformMap.properties
fixes:
```output
20:52:00  Exception in thread "main" java.lang.NullPointerException
20:52:00  	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
20:52:00  	at java.util.regex.Matcher.reset(Matcher.java:309)
20:52:00  	at java.util.regex.Matcher.<init>(Matcher.java:229)
20:52:00  	at java.util.regex.Pattern.matcher(Pattern.java:1093)
20:52:00  	at org.testKitGen.TestInfoParser.checkPlat(TestInfoParser.java:226)
20:52:00  	at org.testKitGen.TestInfoParser.parseVariation(TestInfoParser.java:295)
20:52:00  	at org.testKitGen.TestInfoParser.parse(TestInfoParser.java:93)
20:52:00  	at org.testKitGen.PlaylistInfoParser.parse(PlaylistInfoParser.java:106)
20:52:00  	at org.testKitGen.ParallelGenVisitor.visit(ParallelGenVisitor.java:34)
20:52:00  	at …
```
> Add platformMap for x86-64_solaris

- src/org/testKitGen/TestInfoParser.java
getElementsByTagName("platform") returns all platform nodes in the document including child ones from any <disabled> sections. This PR finds the <platform> element that is directly within the parent element. 
Signed-off-by: Andrew Leonard <anleonar@redhat.com>
> Ensure TestInfoParser gets correct platform element

- openj9Settings.mk
This fixes JDK18 test failure due to reference to `TEST_JRE_BIN` such as
export DYLD_LIBRARY_PATH="/Users/jenkins/workspace/Grinder_TKG/openjdkbinary/openjdk-test-image/openj9:/Users/jenkins/workspace/Grinder_TKG/openjdkbinary/j2sdk-image/Contents/Home/bin/..//**jre**/bin/../lib//default:/Users/jenkins/workspace/Grinder_TKG/openjdkbinary/j2sdk-image/Contents/Home/bin/..//**jre**/bin/../lib//j9vm:";
> JDK_VERSION comparison differentiates JDK18 and JDK8

- scripts/getTestenvProperties.sh
Currently, we take both OPENJ9_BRANCH and OPENJ9_SHA. In testenv.properties, we should set SHA
in OPENJ9_SHA, not OPENJ9_BRANCH.
> Set OPENJ9_SHA in testenv.properties

- scripts/getTestenvProperties.sh
Fixes https://github.com/adoptium/aqa-tests/issues/3208
Running https://ci.adoptopenjdk.net/job/Grinder/2982/console to check
Looks like the same line that caused a problem before has passed without problems:
```
14:33:52  /home/jenkins/workspace/Grinder/aqa-tests/TKG/scripts/getTestenvProperties.sh --repo_dir /home/jenkins/workspace/Grinder/aqa-tests --output_file /home/jenkins/workspace/Grinder/aqa-tests/testenv/testenv.properties --repo_name ADOPTOPENJDK
14:33:52  Check sha in /home/jenkins/workspace/Grinder/aqa-tests and store the info in /home/jenkins/workspace/Grinder/aqa-tests/testenv/testenv.properties
14:33:52  ADOPTOPENJDK_REPO=https://github.com/AdoptOpenJDK/openjdk-tests.git
14:33:52  ADOPTOPENJDK_BRANCH=11c721b16a5906f9e5b35e36b49b1d130d231a01
```
Signed-off-by: Stewart X …
> Replace grep -p with standard UNIX awk operation

- resources/buildPlatformMap.properties
- scripts/resultsSum.pl
This change will make it easier to avoid resubmitting jobs with incorrect parameters when using the Grinder links at the bottom of the console log output. There are two changes here:
1. Previously on 32-bit ARM runs, the Grinder link would set `PLATFORM` to `aarch32_linux`. This is incorrect and this PR adjusts that to be `arm_linux`
2. Some of the parameters use by jenkins, will now be added to the Grinder parameters if they are located in the environment (as they will be for jobs run through jenkins). These will allow the acquisition of the correct source materials used for the testing to take place. The following environment variables are the ones that will now be captured in the grinder re-run logs in the bottom of the console log: `SDK_RESOURCE`, `CUSTOMIZED_SDK_URL`, …
> Allow other jenkins parameters to show in Grinder re-run console links

- openj9Settings.mk
This commit changes the condition for setting VM_SUBDIR in
openj9Settings.mk.
The code without this change sets "compressedrefs" to VM_SUBDIR by
mistake for SPEC like "os_cpu_nocmprssptrs".
Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>
> Set VM_SUBDIR for cmprssptrs in openj9Settings.mk

- .github/workflows/runAqaConfig.json
- scripts/testBot/runAqaArgParse.py
Allow custom repos to be set by the users as command arguments rather than in runAqaConfig.json.
Fixes: adoptium/aqa-tests#3163
Signed-off-by: Nadeen Mohamed <nadeen@ualberta.ca>
> Remove runAqaConfig.json

- featureSettings.mk
There are some tests [1] that fail because the SCC name is too large.
The SCC name when the aot test flag is set is derived from the test
name. In order to prevent this issue, simply use the same name for all
tests. This is ok because prior to and after running tests, all SCCs are
destroyed. Additionally, this does not impact any future ability to run
tests in parallel as this is already not possible; the fact that all
SCCs are destroyed between tests means that one test could impact the
validity of another.
[1] https://github.com/eclipse-openj9/openj9/issues/14461
Fixes https://github.com/eclipse-openj9/openj9/issues/14461
> Use a specific name for SCC

- src/org/openj9/envInfo/MachineInfo.java
Remove the information of EnvDetector's runtime information as it
mislead as the testing jvm information. Helps when tests require os.maxMemory.
Close #302 
> Print OS memory info instead of EnvDetector process's runtime info

- src/org/openj9/envInfo/MachineInfo.java
- src/org/testKitGen/MainRunner.java
- src/org/testKitGen/MkGen.java
- src/org/testKitGen/PlaylistInfoParser.java
- src/org/testKitGen/TestCategory.java
- src/org/testKitGen/TestDivider.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestInfoParser.java
- src/org/testKitGen/TestList.java
- src/org/testKitGen/TestTarget.java
- src/org/testKitGen/Variation.java
- remove detailed logic from TestTarget class
- create class TestList and TestCategory to handle each case
- added logic to handle disabled tests in testList
- keep status inside Variation class for precise control of sub test
- adjust parallel list logic to handle disabled situation
> Support running disabled tests in testList

- settings.mk
openjdkmh is enbaled by default. Change the logic to use exclude file for vt standard build.
Signed-off-by: Hang Shao <hangshao@ca.ibm.com>
> Change the logic to use exclude file

- scripts/resultsSum.pl
choose to run "java -version" instead of get info directly from AQACert.log is because flag AUTO_DETECT need to be enabled for the run. so it is safe to run command
Ref: https://github.com/adoptium/TKG/issues/312
> feat: add java version into TAP file

- scripts/resultsSum.pl
- Add AQACert info in TAP file
- Remove java -version beccause AQACert.log contains java -vesrion
resolves: https://github.com/adoptium/TKG/issues/313
> Add AQACert info in TAP file

- src/org/testKitGen/BuildList.java
- src/org/testKitGen/DirectoryWalker.java
- stop consuming playlist in parent folder when buildlist only contains its subfolder
> Fix issue with TKG traverse

- resources/buildPlatformMap.properties
Fixes the failing Windows aarch64 smoke tests
> add platform map for win_aarch64

- scripts/getDependencies.pl
As a temporary work around to bypass the z/OS issue related to jcstress jar SHA checking (openj9-openjdk-jdk11-zos/issues/1623), use a specific version of jcstress jar. 
Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>
> Use a specific version of jcstress jar to bypass sha file look up which causes issues on z/OS

- featureSettings.mk
- makeGen.mk
- settings.mk
- src/org/testKitGen/Arguments.java
- src/org/testKitGen/MkGen.java
- src/org/testKitGen/TestInfo.java
- src/org/testKitGen/TestInfoParser.java
- add ITERATIONS and AOT_ITERATIONS options
- add option to continue or stop after failure is detected
> Enhance TKG repeat feature

- scripts/resultsSum.pl
Related https://github.com/adoptium/aqa-tests/issues/4146
> Add failed testcase name in tap file

- .github/workflows/codeql-analysis.yml
Fix dependency GitHub action to hash values and restrict to required permissions.
Part of https://github.com/adoptium/adoptium/issues/187
> Fix dependency actions and restrict permissions

- scripts/resultsSum.pl
Support cases that all tests failed with the summary of failed only - Test results: failed: **
related https://github.com/adoptium/aqa-tests/issues/4265
> Update test result regex for all tests failed

- src/org/testKitGen/PlaylistInfoParser.java
In particular, this will reduce the scrolling required to examine logs by eliminating the useless blank lines in output like this:
```
13:29:09  Parsing /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal/aqa-tests/TKG/../functional/cmdLineTests/jrvTest/playlist.xml
13:29:09  
13:29:09  Parsing /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal/aqa-tests/TKG/../functional/cmdLineTests/jvmtitests/playlist.xml
13:29:09  
13:29:09  Parsing /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal/aqa-tests/TKG/../functional/cmdLineTests/jython/playlist.xml
13:29:09  
13:29:09  Parsing /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal/aqa-tests/TKG/../functional/cmdLineTests/laz …
```
> Remove duplicate newlines

- examples/jdkVersion/playlist.xml
- scripts/testTKG/testRunner.py
- src/org/testKitGen/TestInfoParser.java
- update parser logic
- add testcase/example for jdk version
- add testcase/example for disable jdk version
- add verbose option for tkg test
Fixes: #390
> Support defining a range of jdk versions

- .gitignore
- scripts/resultsSum.pl
Support test result as error
Test results: passed: 105; failed: 7; error: 1
test naming ending with #id*
TEST: java/lang/Thread/virtual/stress/PinALot.java#id0
Fix #407 
Fix #408 
> support test failed as error and test naming ending with #id* in tap file

- src/org/openj9/envInfo/MachineInfo.java
- if not rhel, ubuntu and sles, do nothing
- support more oslabel when needed later on
Fixes #431
> Fix issue with oslabel

- scripts/remove_duplicate_tests.py
While the external comments outside the root element tag cannot be preserved due to how the XML Tree is built by the TreeBuilder, the internal comments can be saved and this PR aims at that task
Related #395
> Preserve all internal comments

- src/org/openj9/envInfo/CmdExecutor.java
- src/org/openj9/envInfo/MachineInfo.java
- update curl version command
- switch machineInfo detection to warning mode
- processBuilder to use env copied from the parent shell environment
Fixes #456
> Fix machineInfo curl validation

- scripts/getDependencies.pl
Part of the solution to https://github.com/eclipse-openj9/openj9/issues/17961.
Also put list of jtreg versions in order.
> Also download jtreg-7.3+1

- .gitignore
- examples/feature/playlist.xml
- scripts/testTKG/test_base.py
- scripts/testTKG/test_feature.py
- scripts/testTKG/test_level.py
- src/org/testKitGen/TestInfoParser.java
- modified testInfo parser
- added new tests for feature tag
> Support regex in feature tag

- scripts/getDependencies.xml
-Moved the getJtreg version download logic into TKG/scripts/getDependencies.xml
resolves : https://github.com/adoptium/aqa-tests/issues/4848
> Move getJtreg into getDependencies

- makefile
- scripts/build_tools.xml
- scripts/getDependencies.pl
- scripts/getDependencies.xml
- settings.mk
need to merge with https://github.com/adoptium/aqa-tests/pull/4902
related: https://github.com/adoptium/aqa-tests/issues/4500
> Allow LIB_DIR, customUrl and curlOpts to be set for get dependency logic

- makefile
Fix https://github.com/adoptium/aqa-tests/issues/4914
> Export LIB_DIR

- scripts/getDependencies.xml
Add JDK 23 support in `getDependency`
> Add JDK 23 support in getDependency

- makefile
Update the cygwin check to correctly set LIB_DIR for cygwin os
> Correct CYGWIN LIB_DIR

- src/org/openj9/envInfo/JavaInfo.java
Add a new feature `CRAC`
Currently, `CRAC` is set as `CRIU` when the system property `org.eclipse.openj9.criu.isCRIUCapable` is true.
Related to https://github.com/eclipse-openj9/openj9/pull/18627#discussion_r1442371415
> Add a new feature CRAC

- src/org/openj9/envInfo/JavaInfo.java
`CRaC` is only supported on `Linux amd64`
Verified in [a grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_s390x_linux_testList_0/605/consoleFull)
`-DTEST_FLAG=CRIU` for non-xa64 platform.
This should fix the test compilation error - https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_ojdk292_Personal_testList_0/6/consoleFull
```
11:33:14      [javac] /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_ojdk292_Personal_testList_0/aqa-tests/functional/cmdLineTests/criu/src/org/openj9/criu/TestJDKCRAC.java:31: error: cannot find symbol
11:33:14      [javac] 		Path imagePath = Paths.get(InternalCRIUSupport.getCRaCCheckpointToDir());
11:33:14      [javac] …
```
> CRaC is only supported on Linux amd64

- makefile
Add check of CUT.
CUT is needed for a proper setting of LIB_DIR in CYGWIN.
> Use cut instead of $CUT

- src/org/openj9/envInfo/JavaInfo.java
Add `CRAC` when `org.eclipse.openj9.criu.isCRaCCapable` is set
`CRIU` support is required by `CRaC`.
Depended on
* https://github.com/eclipse-openj9/openj9/pull/18928
FYI @tajila 
> Add CRAC when org.eclipse.openj9.criu.isCRaCCapable is set

- scripts/resultsSum.pl
Update  failed test target output parse in tap file to avoid the information cut and missing
Update jck test cases failed information to be the same way as openjdk tests for diagnostic=failure
Close #439
> Update TAP information for jck tests

- scripts/resultsSum.pl
Jump out of the nested loop to next possible loop.
Update test results regex with `skipped`
fix #508
> Failed test cases 'Finish Time' information is nested.

- examples/base/playlist.xml
- examples/feature/playlist.xml
- examples/hierarchy/a1/b1/playlist.xml
- examples/hierarchy/a2/b2/c2/playlist.xml
- examples/hierarchy/a2/b2/playlist.xml
- examples/hierarchy/a2/d2/playlist.xml
- examples/hierarchy/a2/playlist.xml
- examples/hierarchy/a3/b3/playlist.xml
- examples/hierarchy/a3/c3/d3/playlist.xml
- examples/hierarchy/a3/f3/playlist.xml
- examples/jdkVersion/playlist.xml
- examples/platformRequirements/playlist.xml
- examples/rerun/playlist.xml
- examples/rerun/rerunSub/playlist.xml
- examples/sliceAndDice/level/playlist.xml
Location of xsd schema in example playlist.xml files is wrong. It probably currently does not matter, but should be fixed anyway.
> Fix schema location in playlist.xml files

- scripts/resultsSum.pl
For openjdk and jck tests only.
Testcases result summary per test target and for all running test targets.
Close #510
> Provide testcases result summary

- scripts/resultsSum.pl
Some of other category tests might also run with jtreg. In that case testcase summary per target is still useful.
Related #510
> Limit overall test cases summary for all targets to openjdk and jck only

- resources/ottawa.csv
This commit disables Mode158 on AArch64 Linux.
Mode158 is described as "test 3bit shifting(z/OS only)".
> Disable Mode158 on AArch64 Linux

- examples/platformRequirements/playlist.xml
- makeGen.mk
- scripts/testTKG/test_platformRequirements.py
- src/org/openj9/envInfo/MachineInfo.java
- src/org/testKitGen/TestInfoParser.java
- zlinux version detection
- add tests 
resolves: https://github.com/adoptium/TKG/issues/471
> zlinux micro architecture detection

- scripts/getDependencies.pl
- scripts/getDependencies.xml
fixes: https://github.com/eclipse-openj9/openj9/issues/19435
> Use jtreg 7.3.1+1 for JDK11 tests

- scripts/resultsSum.pl
Make failed test cases visible to TRSS
One part of https://github.com/adoptium/TKG/issues/536
> Adding failed test cases to console

- src/org/openj9/envInfo/JavaInfo.java
added vendor temurin in TKG
Fixes: #535
signed off by Hajer Dahmani <hdahmani@andrew.cmu.edu>
> added vendor temurin in TKG

- scripts/getDependencies.pl
- Enables to avoid system test prerequisite zip file being empty.
related: https://github.com/adoptium/aqa-tests/issues/4912
> Added system test pre-stage jars

- scripts/getDependencies.pl
related: https://github.com/eclipse-openj9/openj9/issues/19582
Reverts adoptium/TKG#533
> Revert "Added system test pre-stage jars"

- scripts/getDependencies.pl
- Enables to avoid system test prerequisite zip file being empty.
- System jars are downloaded under system_lib.
related: adoptium/aqa-tests#4912
related: https://github.com/adoptium/TKG/issues/560
related: https://github.com/adoptium/TKG/issues/561
> Added system test prestage jars

- scripts/getDependencies.pl
The OpenJCEPlus tests require a new test dependency for interop testing with bouncy castle.
Signed-off-by: Jason Katonica <katonica@us.ibm.com>
> Add new dependencies required for OpenJCEPlus tests

- src/org/testKitGen/TestDivider.java
- TKG Parse data from TRSS url
related:https://github.com/adoptium/TKG/issues/558
> Parse data from TRSS url

- src/org/openj9/envInfo/JavaInfo.java
We face this error on linux x86:
```
...
System.getProperty('java.vm.name')=OpenJDK Server VM
System.getProperty('java.vendor')=Red Hat, Inc.
System.getProperty('os.name')=Linux
System.getProperty('os.arch')=i386
System.getProperty('java.fullversion')=null
Cannot determine System.getProperty('os.arch')=i386
make: *** [envDetect] Error 1
...
```
JavaInfo.java should accept `i386` of `os.arch` system property. Seems like value of `os.arch` can be `x86` or `i386` on intel 32-bit, depending on platform. (See also [code](https://github.com/openjdk/jdk8u-dev/blob/fc15e99a3218a88434c27da1d7d09a01c592d8f9/test/lib/jdk/test/lib/Platform.java#L245) in Platform test class.)
> JavaInfo.java: accept osArch i386

- src/org/testKitGen/TestDivider.java
- The platform for aarch64_mac should not include _xl in TRSS url when querying for test execution times,
- Adjusted the code to remove _xl from the platform string if the OS is macOS.
related: https://github.com/adoptium/TKG/issues/557
> Removed _xl for mac platform in TRSS query

- scripts/getDependencies.pl
This update adds maven as a dependency to build and test the OpenJCEPlus project. As part of this effort other dependencies that were used in the past for this project have been removed.
Signed-off-by: Jason Katonica <katonica@us.ibm.com>
> Add maven dependency

- scripts/getDependencies.pl
This PR changes file tagging of testDependency *.jar files from IBM-1047 to BINARY. This PR fixes #600
> Changing tag of jar files to BINARY

- src/org/testKitGen/TestInfoParser.java
This changeset causes variations from `playlist.xml` to be ignored, if `JVM_OPTIONS` env. variable is set. See also: https://github.com/adoptium/TKG/issues/611
**Motivation:**
If `JVM_OPTIONS` env. var is set, jvm opstions for test target get overwritten (including ones set by variation). In this case, test target is still repeated for every variation. However variations no longer make any sense (with overwritten JVM options). It just causes confusion and makes test target run longer.
**Testing:**
with `JVM_OPTIONS` set: [OK](https://ci.adoptium.net/job/Grinder/10879/) (multiple variations are NOT ran)
without `JVM_OPTIONS` set: [OK](https://ci.adoptium.net/job/Grinder/10880/) (multiple variations are ran)
> Ignore variations when JVM_OPTIONS is set

- settings.mk
move JAVA_TO_TEST to the TKG settings.mk
https://github.com/adoptium/aqa-tests/issues/5428
> Issue 5428: Allow JRE testing for other testsuite aside from JCK

- scripts/testTKG/test_platformRequirements.py
- src/org/testKitGen/TestInfoParser.java
- Removed `null` statement from `required` feature check to ensure all required features are processed.
- Allows the code to continue checking all feature flags, even after finding a required flag in `testFlags`.
related:https://github.ibm.com/runtimes/backlog/issues/1525
> Support multiple required in features tag

- settings.mk
The tests mentioned in https://github.com/eclipse-openj9/openj9/issues/12878 are no longer excluded.
> Remove outdated value types issue comment

- scripts/getDependencies.pl
Updating ByteBuddy to include support for JDK 23 and 24.
Related to: https://github.com/eclipse-openj9/openj9/issues/19354
> Update ByteBuddy and ByteBuddyAgent to 1.15.4

- scripts/getDependencies.pl
This PR removes the `tools.jar` dependency from TKG due to the following updates in related repositories:
- **aqa-tests:** Updated to use JDK 17 (instead of JDK 8) to build system test-related jars ([PR 5711](https://github.com/adoptium/aqa-tests/pull/5711)).
- **STF**: Modified to use `tools.jar` from the `java.home/lib` directory ([adoptium/STF#140](https://github.com/adoptium/STF/pull/140)).
related: eclipse-openj9/openj9#19888
> Remove tools.jar dependency from TKG

- src/org/testKitGen/TestInfoParser.java
> checking if JVM_OPTIONS is empty

- src/org/openj9/envInfo/JavaInfo.java
Similar to #640 with jenkins docker pull images, envTf could be an empty string.
> Enhance the check of envTf variable

- scripts/getDependencies.pl
- scripts/getDependencies.xml
This PR to make JDK11 and JDK17 openjdk tests to use jtreg6.1 on z/OS. jtreg7.* has encoding issues on z/OS which led to Malformed Input Error with JDK11 and JDK17 on z/OS.
> Use jtreg6.1 for JDK11/17 on z/OS

- makefile
- src/org/openj9/envInfo/EnvDetector.java
- src/org/openj9/envInfo/Utility.java
- src/org/testKitGen/MkGen.java
- src/org/testKitGen/ModesDictionary.java
- src/org/testKitGen/UtilsGen.java
This PR reverts below commit which exports `IBM_JAVA_OPTIONS to IBM-1047`, as this option isn't required anymore. JDK21 z/OS latest builds works fine without any options.
https://github.com/psoujany/TKG/commit/28c7f761d9d2e60043930c1d699ad79c72c2a29c
defaultCharset of Java21 is UTF-8, TKG scripts which are generating makefiles like utils.mk, rerun.mk are getting created in UTF for 21 on z/OS causing encoding issues. Hence, changing scripts to forcefully create these makefiles in `Charset.forName("IBM-1047")` only for 21 on z/OS.
> Remove IBM-1047 export option and generate makefiles in IBM-1047 encoding for JDK21 on z/OS

- settings.mk
If a macro like `OLD_JAVA_HOME` expands to nothing, the resulting command (`if [ ]; then` ...) is considered syntactically invalid by some versions of bash. This avoids that problem by letting make evaluate the test by using `$(if)`.
See sample failure in https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_Personal_testList_0/236/console
```
13:19:07  Running make 4.3
13:19:07  set TEST_ROOT to C:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-32_windows_Personal_testList_0/aqa-tests/
13:19:07  set JDK_VERSION to 8
13:19:07  set JDK_IMPL to openj9
13:19:07  set JVM_VERSION to openjdk8-openj9
13:19:07  set JCL_VERSION to latest
13:19:07  /bin/sh: -c: line 3: syntax error: unexpected end of file
13:19:07  make[2]: *** [settings.mk:383: …
```
> Fix tests for empty strings in _setup

- .gitignore
- scripts/getSHAs.sh
- scripts/getTestenvProperties.sh
Hashes are now captured in `SHAs.txt` instead of `SHA.txt`.
Fix nearby formatting inconsistencies.
> Update references to SHA.txt -> SHAs.txt

- scripts/getDependencies.pl
- scripts/getDependencies.xml
See [8339238: Update to use jtreg 7.5.1](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/f644a9511ae32adbbeff77b211f82b8d42bdd62d).
> Also download jtreg-7.5+1 and use for Java 25+

- scripts/getDependencies.pl
- scripts/getDependencies.xml
Corrects #673, which should have used 7.5.1+1 instead of 7.5+1; see [8339238: Update to use jtreg 7.5.1](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/f644a9511ae32adbbeff77b211f82b8d42bdd62d).
Depends on https://github.com/adoptium/ci-jenkins-pipelines/pull/1202.
> Also download jtreg-7.5.1+1 and use for Java 25+

- scripts/resultsSum.pl
Fixes https://github.com/adoptium/aqa-tests/issues/6081
Improve resultsSum.pl to recognise openjdk or jck Test results lines.
Some of the regex's were not allowing for ",", and were unnecessarily trying to group the (numeric) value, when just recoginising the error|failed is all that was needed.
Test builds:
TC/job/Test_openjdk24_hs_extended.jck_aarch64_mac/22/console - SUCCESSFUL test result summary and tap file content, and failed tests ReRun
extended.openjdk test: https://ci.adoptium.net/view/Test_openjdk/job/Test_openjdk21_hs_extended.openjdk_aarch64_linux/133/ - SUCCESSFUL test result summary and tap file content
> Correct post test Perl resultsSum processing to correctly handle commas and Test Results line

- scripts/getDependencies.pl
Update `byte-buddy.jar` to enable JDK25 `MockitoMockTest`
Related to 
* https://github.com/eclipse-openj9/openj9/issues/21497
> Update byte-buddy.jar to enable JDK25 MockitoMockTest

- settings.mk
related: [internal issue](https://github.ibm.com/runtimes/openj9-openjdk-jdk21-zos/pull/732#issuecomment-113719145)
> Set JCL_VERSION to latest except for IBM Java8

- scripts/build_test.xml
This PR fixes https://github.ibm.com/runtimes/openj9-openjdk-jdk21-zos/pull/713#issuecomment-111565653 and https://github.ibm.com/runtimes/openj9-openjdk-jdk21-zos/issues/720
> Preserve encoding and tags while copying files on z/OS

- openj9Settings.mk
This change only affects testing with JCL_VERSION=current and JDK_VERSION=8, which is IBM Java8 on Jenkins. Openj9 runs with JCL_VERSION=latest. vmfarm will not be affected as we are running with a fixed TKG level.
resolves: backlog/issues/1656
> Set VM_SUBDIR=compressedrefs for IBM Java 8 if -Xcompressedrefs is used

- scripts/getDependencies.pl
Created new element in 'my %base' for
dacapo-23.11-MR2-chopin-minimal.zip with hash
defined by zip download url, downloaded zip name,
and sha1 value of the downloaded zip.
Fixes: https://github.com/adoptium/aqa-tests/issues/6326
> Added hash for dacapo dependency.

- scripts/getDependencies.pl
Updated maven hash dependency link and sha1 to match version 3.9.10.
Fixes: https://github.com/adoptium/aqa-tests/issues/6336
> Updated maven url and sha1.

- resources/modes.xml
Enable `-Xcheck:jni` by default for `mode 100`
Related to 
* https://github.com/eclipse-openj9/openj9/pull/22199
[A grinder with this change](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/52460/console)
> Enable -Xcheck:jni by default for mode 100

- scripts/getDependencies.pl
- scripts/getDependencies.xml
As part of this issue openj9-openjdk-jdk17-zos/issues/928, we made changes to jtreg code(https://github.com/openjdk/jtreg/pull/267) use defaultCharset() while parsing Test.group files on z/OS. This PR is part of below jtreg archive which we want to use on z/OS for  11/17 releases so that to we use default workspaces.
> Use jtreg_8_2(latest jtreg version) on z/OS across JDK11/17 releases

- resources/ottawa.csv
- Enabled only 64-bit for 110-CS (concurrentScavenge)
related:https://github.com/eclipse-openj9/openj9/issues/22725
> Update ottawa.csv to enable 110-CS only for 64bit
